# Generated by Django 3.2.19 on 2023-05-16 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onlinebooking',
            name='special_request',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
